Issue #5 and Issue #6 - enable custom keystore and truststore config
Alvearie/alvearie-helm pull request #58
Opened 2021-11-04 13:29 UTC by michaelwschroeder

Signed-off-by: Mike Schroeder <mschroed@us.ibm.com>

2021-11-05 19:28 UTC, lmsurpre commented on charts/ibm-fhir-server/README.md.gotmpl
> +By default, the FHIR server is installed with a configuration in the `server.xml` file which includes the definition of a keystore (`fhirKeyStore.p12`) and a truststore (`fhirTrustStore.p12`) file. T
```suggestion
By default, the FHIR server's `server.xml` file includes the definition of a keystore (`fhirKeyStore.p12`) and a truststore (`fhirTrustStore.p12`) file. These files are provided only as examples and, while they may suffice in a test environment, the deployer should generate new keystore and truststore files for any installations where security is a concern.
```

2021-11-05 19:34 UTC, lmsurpre commented on charts/ibm-fhir-server/README.md.gotmpl
> +The keystore Secret is expected to contain the following data:
when we first talked about this I can of assumed `fhirKeyStore` and `fhirKeyStoreFilename` were two different options...
* fhirKeyStore would be to embed the keystore content right into the secret
* fhirKeyStoreFilename would be to point to a file on disk (probably some kind of volume mount)

now that I read this, I guess fhirKeyStoreFilename is actually going to be the file's name?
is that really needed?  maybe its needed so that we can support both jks and p12?

2021-11-06 20:29 UTC, chgl requested changes

2021-11-06 20:29 UTC, chgl commented on charts/ibm-fhir-server/templates/deployment.yaml
> +              mountPath: /opt/ol/wlp/usr/servers/defaultServer/resources/security/${FHIR_KEYSTORE_FILENAME}
Unfortuntely these env vars aren't resolved by Kubernetes, instead this will mount to the file called `${FHIR_KEYSTORE_FILENAME}`, ie. including the `$, {, }` not the actual value.

I think it would be OK to hard-code the file name here, or allow setting the file name inside the values.yaml in plain-text (as opposed to it being part of the secret).

2021-11-06 20:29 UTC, chgl commented on charts/ibm-fhir-server/templates/deployment.yaml
> +              subPath: ${FHIR_KEYSTORE_FILENAME}
Interestingly, you can use an env var here using subPathExpr (https://kubernetes.io/docs/concepts/storage/volumes/#using-subpath-expanded-environment):

```yaml
subPathExpr: $(FHIR_KEYSTORE_FILENAME)
```

But this probably doesn't help much since there is no `mountPathExpr` for L124

2021-11-06 20:29 UTC, chgl commented on charts/ibm-fhir-server/README.md
> +| keyStoreSecret | string | `nil` | Secret containing the FHIR server keystore file and its password. The secret must contain the keys `fhirKeyStore' (the keystore file contents), 'fhirKeyStorePasswo
Does the format of the key store matter? - If it does, it would be helpful to clarify the expected format of the `fhirKeyStore` value here.

2021-11-06 20:34 UTC, chgl commented on charts/ibm-fhir-server/README.md
> +data:
We could use `stringData` here to keep the sample values un-encoded for clarity

2021-11-09 17:52 UTC, michaelwschroeder commented on charts/ibm-fhir-server/README.md.gotmpl
> +By default, the FHIR server is installed with a configuration in the `server.xml` file which includes the definition of a keystore (`fhirKeyStore.p12`) and a truststore (`fhirTrustStore.p12`) file. T
done

2021-11-09 17:56 UTC, michaelwschroeder commented on charts/ibm-fhir-server/README.md.gotmpl
> +The keystore Secret is expected to contain the following data:
Given the issue that @chgl  found with using environment variables in mount paths, I've changed my approach. The secret will now contain only the keystore/truststore file data and the associated password. A new chart value has been added to specify the format of the data. The filename will be hardcoded to `fhirKeyStore` or `fhirTrustStore` with the correct file extension appended based on the format value

2021-11-09 18:00 UTC, michaelwschroeder commented on charts/ibm-fhir-server/templates/deployment.yaml
> +              mountPath: /opt/ol/wlp/usr/servers/defaultServer/resources/security/${FHIR_KEYSTORE_FILENAME}
I've added a new chart value to specify the format (PKCS12 or JKS), and I now hard-code the name of the keystore or truststore file as `fhirKeyStore` or `fhirTrustStore` with the correct file extension appended based on the format specified. So for example, keystore name will be either `fhirKeyStore.p12` or `fhirKeyStore.jks`, depending on the format specified.

2021-11-09 18:02 UTC, michaelwschroeder commented on charts/ibm-fhir-server/README.md
> +| keyStoreSecret | string | `nil` | Secret containing the FHIR server keystore file and its password. The secret must contain the keys `fhirKeyStore' (the keystore file contents), 'fhirKeyStorePasswo
I've added two chart values: `keyStoreFormat` and `trustStoreFormat`. Their descriptions specify allowed values.

2021-11-09 18:03 UTC, michaelwschroeder commented on charts/ibm-fhir-server/README.md
> +data:
I chose to keep as encoded data since I'm not sure how to generate valid stringData for a keystore file.

2021-11-09 19:20 UTC, lmsurpre commented on charts/ibm-fhir-server/README.md.gotmpl
> +The keystore Secret is expected to contain the following data:
works for me

2021-11-09 19:22 UTC, lmsurpre approved these changes
LGTM

2021-11-09 20:10 UTC, chgl commented on charts/ibm-fhir-server/README.md
> +data:
Ah ok, i wasnt sure if the Truststore is just a plaintext pem or something binary. Sure let's keep it as is.

2021-11-09 20:11 UTC, chgl approved these changes

2021-11-09 20:12 UTC, chgl commented on charts/ibm-fhir-server/README.md
> +| keyStoreSecret | string | `nil` | Secret containing the FHIR server keystore file and its password. The secret must contain the keys `fhirKeyStore' (the keystore file contents), 'fhirKeyStorePasswo
Thank you that's definitely clearer now!

2021-11-09 20:47 UTC, merged